### ISSUE TITLE
Matching multi-byte characters like german umlauts

### ISSUE THREAD

**Issue by mbedarff** [svenfuchs/locator#1]
Hello!

Thank you Sven for this Locator GEM! :-) I'm trying to use it with steam to test the ajax functionality of an german rails app on a windows machine. So i want to match german word which contain umlaute like "ä", "ö" and "ü" or the letter "ß". These letters are represented as multibyte letters in UTF8.

It seems that Nokogiri behaves different with Textnodes (class Nokogiri::XML::Text) and attributes (class Nokogiri::XML::Attr). So e.g. the produced HTML code of a view contains this:
        ...
        <span>München</span>
        ...
        <input type="text" value="München"/>
        ...

Then this works and an element is found:
        locate :input, :value => "München"

But this doesn't work (the textnode in the span tag should be found):
        locate "München"

I assume that the reason is the interpretation of the multibyte charcters in Nokogiri's XML lib. Inspecting the html code by calling the method Steam::Browser::HtmlUnit.dom shows that the umlauts in values of attributes are encoded als decimal enties like "M&#252;nchen". But the textnodes are not encoded. There the umlauts appear like "M├╝nchen". I'm using the codepage 1252 because of the "missing a letter"-problem with cucumber under windows.

I have set up JRuby environment with celerity, too. There it works without any problems to match elements by attributes with umlauts AND textnodes containing umlauts:
        browser.text_field(:value => "Müchnchen")
        browser.text.include?("München")
Clerity does not use the Nokogiri XML lib to match elements. I thing it delegates the matching to HtmlUnit.

Yust replacing the umlauts by "ae", "oe" and "ue" in the test data is no workaround because the app has forms with fields which contain umlauts in their labels. So the great fill_in method of the webrat_compatible_steps.rb does not work.

Does anybody share this problem with me (on windows)? Is there a simple solution for this problem?

Cheers, Matthias

**Comment by svenfuchs** [comment]
Hi Matthias,

thanks for reporting this!

I've just added a few tests to replicate this behavior and these tests passed for me: http://github.com/svenfuchs/locator/commit/71180d4dc6fd536a5a90da8cc328117f3fe07233

I then noticed that I'm running them on Ruby 1.9.1 though and switched to 1.8.7. Here one of them breaks with a similar behavior as you describe.

I guess one major point is that your HTML is not really valid HTML when it contains an umlaut like München does. Instead you should encode this umlaut to M&amp;uuml;nchen. If you do that in the test ("locates an element by node name and attribute (containing an umlaut)") this tests passes.

Ok, I guess I might still be able to relax this somehow. Stay tuned.

**Comment by svenfuchs** [comment]
Well, it seems Nokogiri (or libxml?) is a bit intrusive here. Still figuring out how to just transparently pass through un/encoded entities ...

http://stackoverflow.com/questions/2567029/how-to-make-nokogiri-transparently-return-un-encoded-html-entities-untouched

**Comment by svenfuchs** [comment]
Ok, i hope this is fixed (enough) in http://github.com/svenfuchs/locator/commit/7f31143322cc80bab7e406922bfa6f9e22585dbb now :)
